[pytest]
addopts = -p no:cacheprovider
filterwarnings =
    error
    ignore:^Exception ignored in.*<sqlite3\.Connection object:pytest.PytestUnraisableExceptionWarning
    ignore:^Exception ignored while finalizing database connection <sqlite3\.Connection object:pytest.PytestUnraisableExceptionWarning
