from __future__ import annotations

from datetime import UTC, datetime
from typing import Any, Optional

from sqlalchemy import (
    DateTime,
    ForeignKey,
    Integer,
    String,
    Text,
    UniqueConstraint,
    select,
)
from sqlalchemy.orm import (
    Mapped,
    Session,
    mapped_column,
)

from backend.database import Base
from backend.term_service import get_active_term


class OptimizerExecution(Base):
    """
    One grouped multi-step optimizer execution.

    Individual timetable changes remain stored in
    student_schedule_changes.
    """

    __tablename__ = "optimizer_executions"

    id: Mapped[int] = mapped_column(
        Integer,
        primary_key=True,
        autoincrement=True,
    )

    term_id: Mapped[int] = mapped_column(
        ForeignKey("academic_terms.id", ondelete="RESTRICT"),
        nullable=False,
        default=1,
        index=True,
    )

    execution_id: Mapped[str] = mapped_column(
        String(64),
        nullable=False,
        unique=True,
        index=True,
    )

    requested_steps: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
    )

    applied_steps: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
    )

    status: Mapped[str] = mapped_column(
        String(30),
        nullable=False,
        default="running",
    )

    baseline_risk_cost: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
    )

    final_risk_cost: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
    )

    baseline_total_risks: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
    )

    final_total_risks: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
    )

    baseline_student_groups: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
    )

    final_student_groups: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
    )

    baseline_clashes: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
    )

    final_clashes: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
    )

    stop_reason: Mapped[Optional[str]] = mapped_column(
        String(500),
        nullable=True,
    )

    error_message: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime,
        nullable=False,
        default=lambda: datetime.now(UTC).replace(tzinfo=None),
    )

    completed_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime,
        nullable=True,
    )


class OptimizerExecutionStep(Base):
    """
    Links a grouped execution to the existing
    StudentScheduleChange generated by each step.
    """

    __tablename__ = "optimizer_execution_steps"

    __table_args__ = (
        UniqueConstraint(
            "execution_id",
            "step_number",
            name="uq_optimizer_execution_step",
        ),
        UniqueConstraint(
            "execution_id",
            "change_id",
            name="uq_optimizer_execution_change",
        ),
    )

    id: Mapped[int] = mapped_column(
        Integer,
        primary_key=True,
        autoincrement=True,
    )

    execution_id: Mapped[str] = mapped_column(
        String(64),
        nullable=False,
        index=True,
    )

    step_number: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
    )

    change_id: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        index=True,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime,
        nullable=False,
        default=lambda: datetime.now(UTC).replace(tzinfo=None),
    )


def _snapshot_metrics(
    snapshot: dict[str, Any],
) -> dict[str, int]:
    """
    Extract the metrics used by grouped history from a
    global optimizer timetable snapshot.
    """

    clashes = snapshot.get(
        "clashes",
        {},
    )

    risks = snapshot.get(
        "student_risks",
        {},
    )

    return {
        "risk_cost": int(
            snapshot.get(
                "student_risk_cost",
                0,
            )
        ),
        "total_risks": int(
            risks.get(
                "total",
                0,
            )
        ),
        "student_groups": int(
            snapshot.get(
                "student_groups",
                0,
            )
        ),
        "clashes": int(
            clashes.get(
                "total",
                0,
            )
        ),
    }


def get_execution(
    db: Session,
    execution_id: str,
) -> OptimizerExecution | None:
    statement = select(
        OptimizerExecution
    ).where(
        OptimizerExecution.execution_id
        == execution_id
    )

    return db.scalar(
        statement
    )


def create_execution(
    db: Session,
    *,
    execution_id: str,
    requested_steps: int,
    baseline: dict[str, Any],
) -> OptimizerExecution:
    """
    Create one plan-level history record.

    This function only adds/flushes.
    The caller controls the transaction.
    """

    existing = get_execution(
        db,
        execution_id,
    )

    if existing is not None:
        raise ValueError(
            "Optimizer execution already exists."
        )

    metrics = _snapshot_metrics(
        baseline
    )

    execution = OptimizerExecution(
        term_id=get_active_term(db).id,
        execution_id=execution_id,
        requested_steps=requested_steps,
        applied_steps=0,
        status="running",
        baseline_risk_cost=(
            metrics["risk_cost"]
        ),
        final_risk_cost=(
            metrics["risk_cost"]
        ),
        baseline_total_risks=(
            metrics["total_risks"]
        ),
        final_total_risks=(
            metrics["total_risks"]
        ),
        baseline_student_groups=(
            metrics["student_groups"]
        ),
        final_student_groups=(
            metrics["student_groups"]
        ),
        baseline_clashes=(
            metrics["clashes"]
        ),
        final_clashes=(
            metrics["clashes"]
        ),
    )

    db.add(
        execution
    )

    db.flush()

    return execution


def link_execution_step(
    db: Session,
    *,
    execution_id: str,
    step_number: int,
    change_id: int,
) -> OptimizerExecutionStep:
    """
    Link one committed/planned optimizer step to its
    StudentScheduleChange history row.
    """

    link = OptimizerExecutionStep(
        execution_id=execution_id,
        step_number=step_number,
        change_id=change_id,
    )

    db.add(
        link
    )

    db.flush()

    return link


def finalize_execution(
    db: Session,
    *,
    execution_id: str,
    applied_steps: int,
    final_snapshot: dict[str, Any],
    status: str,
    stop_reason: str | None = None,
    error_message: str | None = None,
) -> OptimizerExecution:
    """
    Finalize plan-level history after a successful or
    partially successful optimizer execution.
    """

    execution = get_execution(
        db,
        execution_id,
    )

    if execution is None:
        raise ValueError(
            "Optimizer execution history was not found."
        )

    metrics = _snapshot_metrics(
        final_snapshot
    )

    execution.applied_steps = (
        applied_steps
    )

    execution.status = (
        status
    )

    execution.final_risk_cost = (
        metrics["risk_cost"]
    )

    execution.final_total_risks = (
        metrics["total_risks"]
    )

    execution.final_student_groups = (
        metrics["student_groups"]
    )

    execution.final_clashes = (
        metrics["clashes"]
    )

    execution.stop_reason = (
        stop_reason
    )

    execution.error_message = (
        error_message
    )

    execution.completed_at = (
        datetime.now(UTC).replace(tzinfo=None)
    )

    db.flush()

    return execution


def get_execution_steps(
    db: Session,
    execution_id: str,
) -> list[OptimizerExecutionStep]:
    statement = (
        select(
            OptimizerExecutionStep
        )
        .where(
            OptimizerExecutionStep.execution_id
            == execution_id
        )
        .order_by(
            OptimizerExecutionStep.step_number
        )
    )

    return list(
        db.scalars(
            statement
        ).all()
    )


__all__ = [
    "OptimizerExecution",
    "OptimizerExecutionStep",
    "get_execution",
    "create_execution",
    "link_execution_step",
    "finalize_execution",
    "get_execution_steps",
]
