"""add resolution learning events

Revision ID: 174e0a995fe0
Revises: a875c1fd272c
Create Date: 2026-08-25 13:35:00.417004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '174e0a995fe0'
down_revision: Union[str, Sequence[str], None] = 'a875c1fd272c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resolution_learning_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('change_id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('candidate_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('outcome_label', sa.String(length=20), nullable=False),
    sa.Column('ranker_id', sa.String(length=100), nullable=False),
    sa.Column('ranker_version', sa.String(length=40), nullable=False),
    sa.Column('feature_schema_version', sa.String(length=20), nullable=False),
    sa.Column('safety_status', sa.String(length=30), nullable=False),
    sa.Column('features_json', sa.Text(), nullable=False),
    sa.Column('rank_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("event_type IN ('candidate_applied','resolution_undone','resolution_redone')", name='ck_resolution_learning_events_event_type'),
    sa.CheckConstraint("outcome_label IN ('accepted','undone','redone')", name='ck_resolution_learning_events_outcome_label'),
    sa.CheckConstraint("safety_status IN ('SAFE','CONDITIONALLY_SAFE')", name='ck_resolution_learning_events_safety_status'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['change_id'], ['student_schedule_changes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['student_clash_reports.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['term_id'], ['academic_terms.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resolution_learning_events_candidate_id'), 'resolution_learning_events', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_resolution_learning_events_change_id'), 'resolution_learning_events', ['change_id'], unique=False)
    op.create_index(op.f('ix_resolution_learning_events_created_at'), 'resolution_learning_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_resolution_learning_events_event_type'), 'resolution_learning_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_resolution_learning_events_report_id'), 'resolution_learning_events', ['report_id'], unique=False)
    op.create_index(op.f('ix_resolution_learning_events_term_id'), 'resolution_learning_events', ['term_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resolution_learning_events_term_id'), table_name='resolution_learning_events')
    op.drop_index(op.f('ix_resolution_learning_events_report_id'), table_name='resolution_learning_events')
    op.drop_index(op.f('ix_resolution_learning_events_event_type'), table_name='resolution_learning_events')
    op.drop_index(op.f('ix_resolution_learning_events_created_at'), table_name='resolution_learning_events')
    op.drop_index(op.f('ix_resolution_learning_events_change_id'), table_name='resolution_learning_events')
    op.drop_index(op.f('ix_resolution_learning_events_candidate_id'), table_name='resolution_learning_events')
    op.drop_table('resolution_learning_events')
    # ### end Alembic commands ###
