"""add student clash reporting

Revision ID: 35eb6b025f30
Revises: 90feb9f09ea3
Create Date: 2026-08-24 20:15:34.893623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35eb6b025f30'
down_revision: Union[str, Sequence[str], None] = '90feb9f09ea3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_clash_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('evidence_reference', sa.String(length=500), nullable=True),
    sa.Column('duplicate_of_report_id', sa.Integer(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('submitted','under_review','resolved','rejected','duplicate')", name='ck_student_clash_reports_status'),
    sa.ForeignKeyConstraint(['duplicate_of_report_id'], ['student_clash_reports.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_clash_reports_duplicate_of_report_id'), 'student_clash_reports', ['duplicate_of_report_id'], unique=False)
    op.create_index(op.f('ix_student_clash_reports_status'), 'student_clash_reports', ['status'], unique=False)
    op.create_index(op.f('ix_student_clash_reports_student_user_id'), 'student_clash_reports', ['student_user_id'], unique=False)
    op.create_table('student_clash_report_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['student_clash_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_clash_report_events_report_id'), 'student_clash_report_events', ['report_id'], unique=False)
    op.create_table('student_clash_report_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('timetable_entry_id', sa.Integer(), nullable=True),
    sa.Column('course_code', sa.String(length=50), nullable=False),
    sa.Column('section', sa.String(length=50), nullable=True),
    sa.Column('semester', sa.String(length=50), nullable=True),
    sa.Column('day', sa.String(length=20), nullable=True),
    sa.Column('start_time', sa.String(length=10), nullable=True),
    sa.Column('end_time', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['student_clash_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['timetable_entry_id'], ['timetable_entries.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_clash_report_items_report_id'), 'student_clash_report_items', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_clash_report_items_report_id'), table_name='student_clash_report_items')
    op.drop_table('student_clash_report_items')
    op.drop_index(op.f('ix_student_clash_report_events_report_id'), table_name='student_clash_report_events')
    op.drop_table('student_clash_report_events')
    op.drop_index(op.f('ix_student_clash_reports_student_user_id'), table_name='student_clash_reports')
    op.drop_index(op.f('ix_student_clash_reports_status'), table_name='student_clash_reports')
    op.drop_index(op.f('ix_student_clash_reports_duplicate_of_report_id'), table_name='student_clash_reports')
    op.drop_table('student_clash_reports')
    # ### end Alembic commands ###
