"""add pii guarded domain learning events

Revision ID: 738057d5ac81
Revises: b8438f7b555a
Create Date: 2026-08-25 14:38:21.269500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '738057d5ac81'
down_revision: Union[str, Sequence[str], None] = 'b8438f7b555a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('subject_key', sa.String(length=64), nullable=True),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_key', sa.String(length=64), nullable=False),
    sa.Column('actor_role', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('outcome_label', sa.String(length=50), nullable=True),
    sa.Column('context_schema_version', sa.String(length=20), nullable=False),
    sa.Column('context_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("actor_role IS NULL OR actor_role IN ('student','faculty','coordinator','admin','system')", name='ck_learning_events_actor_role'),
    sa.CheckConstraint("event_type IN ('recommendation_generated','recommendation_shown','recommendation_selected','recommendation_rejected','resolution_applied','resolution_undone','resolution_redone','manual_timetable_change','student_enrolled','student_dropped','clash_report_submitted','clash_report_verified','clash_report_invalid','clash_report_duplicate','term_archived')", name='ck_learning_events_event_type'),
    sa.ForeignKeyConstraint(['term_id'], ['academic_terms.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_events_entity_key'), 'learning_events', ['entity_key'], unique=False)
    op.create_index(op.f('ix_learning_events_term_id'), 'learning_events', ['term_id'], unique=False)
    op.create_index('ix_learning_events_type_created', 'learning_events', ['event_type', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_learning_events_type_created', table_name='learning_events')
    op.drop_index(op.f('ix_learning_events_term_id'), table_name='learning_events')
    op.drop_index(op.f('ix_learning_events_entity_key'), table_name='learning_events')
    op.drop_table('learning_events')
    # ### end Alembic commands ###
