"""add faculty class assignments

Revision ID: 8bc9d5936376
Revises: 35eb6b025f30
Create Date: 2026-08-24 20:25:46.436063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bc9d5936376'
down_revision: Union[str, Sequence[str], None] = '35eb6b025f30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculty_class_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('faculty_user_id', sa.Integer(), nullable=False),
    sa.Column('course_code', sa.String(length=50), nullable=False),
    sa.Column('section', sa.String(length=50), nullable=False),
    sa.Column('semester', sa.String(length=50), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['faculty_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('faculty_user_id', 'course_code', 'section', 'semester', name='uq_faculty_class_assignment_identity')
    )
    op.create_index(op.f('ix_faculty_class_assignments_faculty_user_id'), 'faculty_class_assignments', ['faculty_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_faculty_class_assignments_faculty_user_id'), table_name='faculty_class_assignments')
    op.drop_table('faculty_class_assignments')
    # ### end Alembic commands ###
