"""add institutional scheduling foundation

Revision ID: a8479a74c680
Revises: 738057d5ac81
Create Date: 2026-08-28 17:38:06.686057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8479a74c680'
down_revision: Union[str, Sequence[str], None] = '738057d5ac81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculty_teaching_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('designation', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("designation IN ('lecturer','assistant_professor')", name='ck_faculty_teaching_profiles_designation'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('course_offerings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('course_code', sa.String(length=50), nullable=False),
    sa.Column('course_name', sa.String(length=150), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=50), nullable=False),
    sa.Column('class_type', sa.String(length=20), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('room', sa.String(length=150), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("class_type IN ('lecture','lab')", name='ck_course_offerings_class_type'),
    sa.CheckConstraint('duration_minutes >= 30 AND duration_minutes <= 240', name='ck_course_offerings_duration'),
    sa.CheckConstraint('semester >= 1 AND semester <= 8', name='ck_course_offerings_semester'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['term_id'], ['academic_terms.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('term_id', 'course_code', 'semester', 'section', 'class_type', name='uq_course_offering_identity')
    )
    op.create_index(op.f('ix_course_offerings_course_code'), 'course_offerings', ['course_code'], unique=False)
    op.create_index(op.f('ix_course_offerings_semester'), 'course_offerings', ['semester'], unique=False)
    op.create_index(op.f('ix_course_offerings_term_id'), 'course_offerings', ['term_id'], unique=False)
    op.create_table('faculty_availability_windows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('faculty_user_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.String(length=5), nullable=False),
    sa.Column('end_time', sa.String(length=5), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("day IN ('Monday','Tuesday','Wednesday','Thursday','Friday')", name='ck_faculty_availability_windows_day'),
    sa.CheckConstraint('start_time < end_time', name='ck_faculty_availability_windows_time_order'),
    sa.ForeignKeyConstraint(['faculty_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['academic_terms.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('term_id', 'faculty_user_id', 'day', 'start_time', 'end_time', name='uq_faculty_availability_window_identity')
    )
    op.create_index(op.f('ix_faculty_availability_windows_faculty_user_id'), 'faculty_availability_windows', ['faculty_user_id'], unique=False)
    op.create_index(op.f('ix_faculty_availability_windows_term_id'), 'faculty_availability_windows', ['term_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_faculty_availability_windows_term_id'), table_name='faculty_availability_windows')
    op.drop_index(op.f('ix_faculty_availability_windows_faculty_user_id'), table_name='faculty_availability_windows')
    op.drop_table('faculty_availability_windows')
    op.drop_index(op.f('ix_course_offerings_term_id'), table_name='course_offerings')
    op.drop_index(op.f('ix_course_offerings_semester'), table_name='course_offerings')
    op.drop_index(op.f('ix_course_offerings_course_code'), table_name='course_offerings')
    op.drop_table('course_offerings')
    op.drop_table('faculty_teaching_profiles')
    # ### end Alembic commands ###
