"""Initial database schema

Revision ID: b587dc3b5e56
Revises: 
Create Date: 2026-08-24 08:53:03.668931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b587dc3b5e56'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('optimizer_execution_steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('execution_id', sa.String(length=64), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('change_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('execution_id', 'change_id', name='uq_optimizer_execution_change'),
    sa.UniqueConstraint('execution_id', 'step_number', name='uq_optimizer_execution_step')
    )
    op.create_index(op.f('ix_optimizer_execution_steps_change_id'), 'optimizer_execution_steps', ['change_id'], unique=False)
    op.create_index(op.f('ix_optimizer_execution_steps_execution_id'), 'optimizer_execution_steps', ['execution_id'], unique=False)
    op.create_table('optimizer_executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('execution_id', sa.String(length=64), nullable=False),
    sa.Column('requested_steps', sa.Integer(), nullable=False),
    sa.Column('applied_steps', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('baseline_risk_cost', sa.Integer(), nullable=False),
    sa.Column('final_risk_cost', sa.Integer(), nullable=False),
    sa.Column('baseline_total_risks', sa.Integer(), nullable=False),
    sa.Column('final_total_risks', sa.Integer(), nullable=False),
    sa.Column('baseline_student_groups', sa.Integer(), nullable=False),
    sa.Column('final_student_groups', sa.Integer(), nullable=False),
    sa.Column('baseline_clashes', sa.Integer(), nullable=False),
    sa.Column('final_clashes', sa.Integer(), nullable=False),
    sa.Column('stop_reason', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimizer_executions_execution_id'), 'optimizer_executions', ['execution_id'], unique=True)
    op.create_table('timetable_changes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('old_room', sa.String(length=150), nullable=True),
    sa.Column('new_room', sa.String(length=150), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('undone', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timetable_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entry_kind', sa.String(length=30), nullable=False),
    sa.Column('course_code', sa.String(length=50), nullable=True),
    sa.Column('course_name', sa.String(length=150), nullable=True),
    sa.Column('semester', sa.String(length=50), nullable=True),
    sa.Column('section', sa.String(length=50), nullable=True),
    sa.Column('faculty', sa.String(length=150), nullable=True),
    sa.Column('room', sa.String(length=150), nullable=True),
    sa.Column('day', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.String(length=10), nullable=False),
    sa.Column('end_time', sa.String(length=10), nullable=False),
    sa.Column('class_type', sa.String(length=30), nullable=False),
    sa.Column('raw_text', sa.String(length=500), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_schedule_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('old_day', sa.String(length=20), nullable=False),
    sa.Column('old_start_time', sa.String(length=10), nullable=False),
    sa.Column('old_end_time', sa.String(length=10), nullable=False),
    sa.Column('new_day', sa.String(length=20), nullable=False),
    sa.Column('new_start_time', sa.String(length=10), nullable=False),
    sa.Column('new_end_time', sa.String(length=10), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('reasons_json', sa.Text(), nullable=True),
    sa.Column('risk_cost_before', sa.Integer(), nullable=False),
    sa.Column('risk_cost_after', sa.Integer(), nullable=False),
    sa.Column('total_risks_before', sa.Integer(), nullable=False),
    sa.Column('total_risks_after', sa.Integer(), nullable=False),
    sa.Column('undone', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['timetable_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_schedule_changes_entry_id'), 'student_schedule_changes', ['entry_id'], unique=False)
    op.create_index(op.f('ix_student_schedule_changes_id'), 'student_schedule_changes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_schedule_changes_id'), table_name='student_schedule_changes')
    op.drop_index(op.f('ix_student_schedule_changes_entry_id'), table_name='student_schedule_changes')
    op.drop_table('student_schedule_changes')
    op.drop_table('timetable_entries')
    op.drop_table('timetable_changes')
    op.drop_index(op.f('ix_optimizer_executions_execution_id'), table_name='optimizer_executions')
    op.drop_table('optimizer_executions')
    op.drop_index(op.f('ix_optimizer_execution_steps_execution_id'), table_name='optimizer_execution_steps')
    op.drop_index(op.f('ix_optimizer_execution_steps_change_id'), table_name='optimizer_execution_steps')
    op.drop_table('optimizer_execution_steps')
    # ### end Alembic commands ###
