"""harden scheduling and token sessions

Revision ID: cdc41630067f
Revises: 265967d12f03
Create Date: 2026-08-25 00:10:42.974130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdc41630067f'
down_revision: Union[str, Sequence[str], None] = '265967d12f03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_timetable_entries_course_code'), 'timetable_entries', ['course_code'], unique=False)
    op.create_index(op.f('ix_timetable_entries_day'), 'timetable_entries', ['day'], unique=False)
    op.create_index(op.f('ix_timetable_entries_room'), 'timetable_entries', ['room'], unique=False)
    op.add_column(
        'users',
        sa.Column(
            'token_version',
            sa.Integer(),
            server_default=sa.text('0'),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_version')
    op.drop_index(op.f('ix_timetable_entries_room'), table_name='timetable_entries')
    op.drop_index(op.f('ix_timetable_entries_day'), table_name='timetable_entries')
    op.drop_index(op.f('ix_timetable_entries_course_code'), table_name='timetable_entries')
    # ### end Alembic commands ###
