"""add timetable time change history

Revision ID: ee8c90bdac09
Revises: cdc41630067f
Create Date: 2026-08-25 01:33:42.787984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee8c90bdac09'
down_revision: Union[str, Sequence[str], None] = 'cdc41630067f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timetable_changes', sa.Column('old_day', sa.String(length=20), nullable=True))
    op.add_column('timetable_changes', sa.Column('new_day', sa.String(length=20), nullable=True))
    op.add_column('timetable_changes', sa.Column('old_start_time', sa.String(length=10), nullable=True))
    op.add_column('timetable_changes', sa.Column('new_start_time', sa.String(length=10), nullable=True))
    op.add_column('timetable_changes', sa.Column('old_end_time', sa.String(length=10), nullable=True))
    op.add_column('timetable_changes', sa.Column('new_end_time', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timetable_changes', 'new_end_time')
    op.drop_column('timetable_changes', 'old_end_time')
    op.drop_column('timetable_changes', 'new_start_time')
    op.drop_column('timetable_changes', 'old_start_time')
    op.drop_column('timetable_changes', 'new_day')
    op.drop_column('timetable_changes', 'old_day')
    # ### end Alembic commands ###
