import { KeyRound, UserRound } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { authApi } from '../api/auth'
import { ApiError } from '../api/client'
import { Field, Input } from '../components/Form'
import { ErrorNote, PageHeader, Section, StatusBadge, SuccessNote } from '../components/Ui'
import { useAuth } from '../features/auth/AuthContext'
import { roleLabel } from '../utils/format'

export function AccountPage() {
  const { user, setUser, logout } = useAuth(); const [name, setName] = useState(user?.full_name || ''); const [profileMessage, setProfileMessage] = useState(''); const [profileError, setProfileError] = useState('')
  const [currentPassword, setCurrentPassword] = useState(''); const [newPassword, setNewPassword] = useState(''); const [passwordMessage, setPasswordMessage] = useState(''); const [passwordError, setPasswordError] = useState('')
  const [profileBusy, setProfileBusy] = useState(false); const [passwordBusy, setPasswordBusy] = useState(false)
  if (!user) return null
  async function updateProfile(event: FormEvent) { event.preventDefault(); if (profileBusy) return; setProfileBusy(true); setProfileError(''); setProfileMessage(''); try { const updated = await authApi.updateProfile(name); setUser(updated); setProfileMessage('Profile updated.') } catch (err) { setProfileError(err instanceof ApiError ? err.message : 'Unable to update profile.') } finally { setProfileBusy(false) } }
  async function changePassword(event: FormEvent) { event.preventDefault(); if (passwordBusy) return; setPasswordBusy(true); setPasswordError(''); setPasswordMessage(''); try { await authApi.changePassword(currentPassword, newPassword); setCurrentPassword(''); setNewPassword(''); setPasswordMessage('Password changed. Existing access tokens are invalidated; please sign in again.'); setTimeout(logout, 900) } catch (err) { setPasswordError(err instanceof ApiError ? err.message : 'Unable to change password.'); setPasswordBusy(false) } }
  return <div className="page"><PageHeader title="Account" description="Manage the profile and password attached to your authenticated UniTime-AI account."/><div className="two-column"><Section title="Profile" description="Your role and email are controlled by the backend account system."><div className="profile-summary"><div className="profile-summary__avatar">{user.full_name.slice(0,1)}</div><div><strong>{user.full_name}</strong><span>{user.email}</span><StatusBadge tone="info">{roleLabel(user.role)}</StatusBadge></div></div><form className="form-stack" onSubmit={updateProfile}><Field label="Full name"><Input value={name} onChange={(e) => setName(e.target.value)} minLength={2} maxLength={200} required/></Field>{profileError && <ErrorNote>{profileError}</ErrorNote>}{profileMessage && <SuccessNote>{profileMessage}</SuccessNote>}<button className="btn btn--primary" disabled={profileBusy}><UserRound size={16}/>{profileBusy ? 'Saving…' : 'Save profile'}</button></form></Section><Section title="Change password" description="Changing your password invalidates previously issued access tokens."><form className="form-stack" onSubmit={changePassword}><Field label="Current password"><Input type="password" value={currentPassword} onChange={(e) => setCurrentPassword(e.target.value)} required/></Field><Field label="New password" hint="8–128 characters"><Input type="password" value={newPassword} onChange={(e) => setNewPassword(e.target.value)} minLength={8} maxLength={128} required/></Field>{passwordError && <ErrorNote>{passwordError}</ErrorNote>}{passwordMessage && <SuccessNote>{passwordMessage}</SuccessNote>}<button className="btn btn--secondary" disabled={passwordBusy}><KeyRound size={16}/>{passwordBusy ? 'Changing…' : 'Change password'}</button></form></Section></div></div>
}
