import { Plus, Search } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { adminApi } from '../api/admin'
import { ApiError } from '../api/client'
import { Field, Input, Select } from '../components/Form'
import { EmptyState, ErrorNote, ErrorState, LoadingState, Modal, PageHeader, Pagination, Section, StatusBadge, SuccessNote } from '../components/Ui'
import { useAsync } from '../hooks/useAsync'
import { useDebouncedValue } from '../hooks/useDebouncedValue'
import type { User, UserRole } from '../types/api'
import { roleLabel } from '../utils/format'

const roles: UserRole[] = ['student','faculty','coordinator','admin']
const PAGE_SIZE = 25

export function AdminUsersPage() {
  const [search, setSearch] = useState(''); const [role, setRole] = useState<UserRole | ''>(''); const [active, setActive] = useState<boolean | ''>(''); const [offset, setOffset] = useState(0); const [createOpen, setCreateOpen] = useState(false); const [editUser, setEditUser] = useState<User | null>(null); const [message, setMessage] = useState('')
  const debouncedSearch = useDebouncedValue(search)
  const users = useAsync(() => adminApi.users({ search: debouncedSearch, role, isActive: active, offset, limit: PAGE_SIZE }), [debouncedSearch, role, active, offset])
  return <div className="page"><PageHeader title="Users & roles" description="Admin-only account management. Public student registration never grants privileged roles." actions={<button className="btn btn--primary" onClick={() => setCreateOpen(true)}><Plus size={16}/>Create user</button>}/>{message && <SuccessNote>{message}</SuccessNote>}<div className="toolbar toolbar--filters"><label className="search-box"><Search size={17}/><input value={search} onChange={(e) => { setSearch(e.target.value); setOffset(0) }} placeholder="Search name or email"/></label><Select value={role} onChange={(e) => { setRole(e.target.value as UserRole | ''); setOffset(0) }}><option value="">All roles</option>{roles.map((item) => <option key={item} value={item}>{roleLabel(item)}</option>)}</Select><Select value={String(active)} onChange={(e) => { setActive(e.target.value === '' ? '' : e.target.value === 'true'); setOffset(0) }}><option value="">All states</option><option value="true">Active</option><option value="false">Inactive</option></Select></div><Section>{users.loading ? <LoadingState/> : users.error ? <ErrorState message={users.error} retry={users.reload}/> : users.data?.users.length ? <div className="table-wrap"><table className="data-table"><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Action</th></tr></thead><tbody>{users.data.users.map((item) => <tr key={item.id}><td><strong>{item.full_name}</strong><small>{item.email}</small></td><td>{roleLabel(item.role)}</td><td><StatusBadge tone={item.is_active ? 'success' : 'neutral'}>{item.is_active ? 'Active' : 'Inactive'}</StatusBadge></td><td><button className="btn btn--ghost" onClick={() => setEditUser(item)}>Manage</button></td></tr>)}</tbody></table></div> : <EmptyState title="No users match" description="Adjust the filters or create a new authorized account."/>}{users.data && <Pagination total={users.data.total} offset={users.data.offset} limit={users.data.limit} label="users" onChange={setOffset}/>}</Section>{createOpen && <CreateUserModal onClose={() => setCreateOpen(false)} onSaved={async () => { setCreateOpen(false); setMessage('User created.'); await users.reload() }}/>} {editUser && <EditUserModal user={editUser} onClose={() => setEditUser(null)} onSaved={async () => { setEditUser(null); setMessage('User updated.'); await users.reload() }}/>}</div>
}

function CreateUserModal({ onClose, onSaved }: { onClose: () => void; onSaved: () => Promise<void> }) { const [name,setName]=useState(''); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [role,setRole]=useState<UserRole>('faculty'); const [error,setError]=useState(''); const [busy,setBusy]=useState(false); async function submit(e:FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{await adminApi.createUser({full_name:name,email,password,role});await onSaved()}catch(err){setError(err instanceof ApiError?err.message:'Unable to create user.')}finally{setBusy(false)}} return <Modal title="Create authorized user" onClose={onClose}><form className="form-stack" onSubmit={submit}><Field label="Full name"><Input value={name} onChange={(e)=>setName(e.target.value)} maxLength={200} required/></Field><Field label="Email"><Input type="email" value={email} onChange={(e)=>setEmail(e.target.value)} required/></Field><Field label="Password"><Input type="password" value={password} onChange={(e)=>setPassword(e.target.value)} minLength={8} maxLength={128} required/></Field><Field label="Role"><Select value={role} onChange={(e)=>setRole(e.target.value as UserRole)}>{roles.map((item)=><option value={item} key={item}>{roleLabel(item)}</option>)}</Select></Field>{error&&<ErrorNote>{error}</ErrorNote>}<div className="modal-actions"><button type="button" className="btn btn--secondary" disabled={busy} onClick={onClose}>Cancel</button><button className="btn btn--primary" disabled={busy}>{busy?'Creating…':'Create user'}</button></div></form></Modal> }

function EditUserModal({ user, onClose, onSaved }: { user: User; onClose: () => void; onSaved: () => Promise<void> }) { const [name,setName]=useState(user.full_name); const [role,setRole]=useState<UserRole>(user.role); const [active,setActive]=useState(user.is_active); const [error,setError]=useState(''); const [busy,setBusy]=useState(false); async function submit(e:FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{await adminApi.updateUser(user.id,{full_name:name,role,is_active:active});await onSaved()}catch(err){setError(err instanceof ApiError?err.message:'Unable to update user.')}finally{setBusy(false)}} return <Modal title={`Manage ${user.full_name}`} onClose={onClose}><form className="form-stack" onSubmit={submit}><Field label="Full name"><Input value={name} onChange={(e)=>setName(e.target.value)} maxLength={200} required/></Field><Field label="Role"><Select value={role} onChange={(e)=>setRole(e.target.value as UserRole)}>{roles.map((item)=><option key={item} value={item}>{roleLabel(item)}</option>)}</Select></Field><label className="switch-row"><div><strong>Account active</strong><span>Inactive accounts cannot authenticate.</span></div><input type="checkbox" checked={active} onChange={(e)=>setActive(e.target.checked)}/></label>{error&&<ErrorNote>{error}</ErrorNote>}<div className="modal-actions"><button type="button" className="btn btn--secondary" disabled={busy} onClick={onClose}>Cancel</button><button className="btn btn--primary" disabled={busy}>{busy?'Saving…':'Save changes'}</button></div></form></Modal> }
