import { ArrowRight, Clock3, FileText, Plus, UserRound } from 'lucide-react'
import { useMemo, useState, type FormEvent } from 'react'
import { reportsApi } from '../api/reports'
import { studentApi } from '../api/student'
import { ApiError } from '../api/client'
import { Field, Input, Select, Textarea } from '../components/Form'
import { EmptyState, ErrorState, LoadingState, Modal, PageHeader, Pagination, Section, StatusBadge, SuccessNote } from '../components/Ui'
import { useAuth } from '../features/auth/AuthContext'
import { useAsync } from '../hooks/useAsync'
import type { ClashReportDetail, ClashReportResolutionReason, ClashReportStatus } from '../types/api'
import { formatClock, formatRelative, statusTone, titleCase } from '../utils/format'

const statuses: ClashReportStatus[] = ['submitted','under_review','resolved','rejected','duplicate']
const resolutionReasons: ClashReportResolutionReason[] = ['timetable_changed','enrollment_corrected','course_dropped','other_verified_correction']
const PAGE_SIZE = 20

export function ClashReportsPage() {
  const { user } = useAuth(); const reviewer = user && ['coordinator','admin'].includes(user.role)
  const [status, setStatus] = useState<ClashReportStatus | ''>(''); const [offset, setOffset] = useState(0); const [selected, setSelected] = useState<number | null>(null); const [createOpen, setCreateOpen] = useState(false); const [message, setMessage] = useState('')
  const reports = useAsync(() => reviewer ? reportsApi.queue(status, offset, PAGE_SIZE) : studentApi.clashReports(offset, PAGE_SIZE), [reviewer, status, offset])
  const detail = useAsync(async () => selected ? (reviewer ? reportsApi.detail(selected) : studentApi.clashReport(selected)) : null, [selected, reviewer])
  return <div className="page"><PageHeader title={reviewer ? 'Student clash reports' : 'Clash reports'} description={reviewer ? 'Review timetable cases submitted by students, follow the allowed lifecycle, and document the resolution.' : 'Submit timetable clashes without visiting the coordinator office, then track their status here.'} actions={!reviewer ? <button className="btn btn--primary" onClick={() => setCreateOpen(true)}><Plus size={16}/>New report</button> : undefined}/>
    {message && <SuccessNote>{message}</SuccessNote>}
    {reviewer && <div className="toolbar"><Field label="Status filter"><Select value={status} onChange={(e) => { setStatus(e.target.value as ClashReportStatus | ''); setOffset(0); setSelected(null) }}><option value="">All statuses</option>{statuses.map((item) => <option key={item} value={item}>{titleCase(item)}</option>)}</Select></Field></div>}
    {reports.loading ? <LoadingState/> : reports.error ? <ErrorState message={reports.error} retry={reports.reload}/> : reports.data?.reports.length ? <div className="case-layout"><Section className="case-list-section"><div className="case-list">{reports.data.reports.map((report) => <button key={report.id} className={`case-row ${selected === report.id ? 'case-row--active' : ''}`} onClick={() => setSelected(report.id)}><div className="case-row__top"><strong>#{report.id} {reviewer && `· ${report.student_name}`}</strong><StatusBadge tone={statusTone(report.status)}>{titleCase(report.status)}</StatusBadge></div><span>{report.items.map((item) => item.course_code).join(' ↔ ')}</span><small><Clock3 size={13}/>{formatRelative(report.created_at)}</small></button>)}</div></Section><Section className="case-detail-section">{selected ? detail.loading ? <LoadingState/> : detail.error ? <ErrorState message={detail.error}/> : detail.data ? <ReportDetail report={detail.data} reviewer={Boolean(reviewer)} onUpdated={async (text) => { setMessage(text); await reports.reload(); await detail.reload() }}/> : null : <EmptyState title="Select a report" description="Choose a case from the queue to inspect its classes, notes and audit history."/>}</Section></div> : <EmptyState title={reviewer ? 'No reports in this queue' : 'No clash reports yet'} description={reviewer ? 'Try another status filter or check back when students submit new cases.' : 'If two of your enrolled classes overlap, create a report here.'} action={!reviewer ? <button className="btn btn--primary" onClick={() => setCreateOpen(true)}>Create report</button> : undefined}/>}
    {reports.data && <Pagination total={reports.data.total} offset={reports.data.offset} limit={reports.data.limit} label="reports" onChange={(next) => { setOffset(next); setSelected(null) }}/>}
    {createOpen && <CreateReportModal onClose={() => setCreateOpen(false)} onCreated={async () => { setCreateOpen(false); setOffset(0); setMessage('Clash report submitted.'); await reports.reload() }}/>}
  </div>
}

function ReportDetail({ report, reviewer, onUpdated }: { report: ClashReportDetail; reviewer: boolean; onUpdated: (message: string) => Promise<void> }) {
  const [reviewOpen, setReviewOpen] = useState(false)
  return <div className="case-detail"><div className="case-detail__heading"><div><span className="eyebrow">Case #{report.id}</span><h2>{report.items.map((item) => item.course_code).join(' ↔ ')}</h2>{reviewer && <p><UserRound size={14}/>{report.student_name} · {report.student_email}</p>}</div><StatusBadge tone={statusTone(report.status)}>{titleCase(report.status)}</StatusBadge></div><div className="case-classes">{report.items.map((item) => <article key={item.id}><strong>{item.course_code}</strong><span>{item.section ? `Section ${item.section}` : 'Shared session'}</span><small>{item.day || 'Day unavailable'} · {formatClock(item.start_time)} – {formatClock(item.end_time)}</small></article>)}</div>{report.notes && <div className="case-note"><FileText size={17}/><div><strong>Student notes</strong><p>{report.notes}</p></div></div>}{report.evidence_reference && <div className="case-note"><strong>Evidence reference</strong><p>{report.evidence_reference}</p></div>}{report.resolution_note && <div className="resolution-note"><strong>Resolution{report.resolution_reason ? ` · ${titleCase(report.resolution_reason)}` : ''}</strong><p>{report.resolution_note}</p></div>}<div className="timeline"><h3>Case history</h3>{report.events.map((event) => <div className="timeline__item" key={event.id}><span/><div><strong>{titleCase(event.action)}</strong><p>{event.from_status && event.to_status ? `${titleCase(event.from_status)} → ${titleCase(event.to_status)}` : event.note || 'Case activity recorded'}</p><small>{formatRelative(event.created_at)}</small></div></div>)}</div>{reviewer && ['submitted','under_review'].includes(report.status) && <button className="btn btn--primary" onClick={() => setReviewOpen(true)}>Update case <ArrowRight size={16}/></button>}{reviewOpen && <ReviewModal report={report} onClose={() => setReviewOpen(false)} onSaved={async () => { setReviewOpen(false); await onUpdated('Clash report updated.') }}/>}</div>
}

function CreateReportModal({ onClose, onCreated }: { onClose: () => void; onCreated: () => Promise<void> }) {
  const timetable = useAsync(() => studentApi.timetable(), [])
  const [selected, setSelected] = useState<number[]>([]); const [notes, setNotes] = useState(''); const [evidence, setEvidence] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  const selectedEntries = useMemo(() => (timetable.data || []).filter((entry) => selected.includes(entry.id)), [timetable.data, selected])
  function toggle(id: number) { setSelected((current) => current.includes(id) ? current.filter((item) => item !== id) : current.length < 10 ? [...current, id] : current) }
  async function submit(event: FormEvent) { event.preventDefault(); if (selected.length < 2) { setError('Select at least two timetable entries.'); return } setBusy(true); setError(''); try { await studentApi.submitClashReport({ timetable_entry_ids: selected, notes: notes || null, evidence_reference: evidence || null }); await onCreated() } catch (err) { setError(err instanceof ApiError ? err.message : 'Unable to submit report.') } finally { setBusy(false) } }
  return <Modal title="Report a timetable clash" onClose={onClose} wide><form className="form-stack" onSubmit={submit}><div><strong>Select 2–10 classes</strong><p className="muted">The backend verifies that every selected class belongs to your personal timetable and that at least one pair overlaps.</p></div>{timetable.loading ? <LoadingState/> : <div className="selectable-classes">{timetable.data?.map((entry) => <label key={entry.id} className={selected.includes(entry.id) ? 'selected' : ''}><input type="checkbox" checked={selected.includes(entry.id)} onChange={() => toggle(entry.id)}/><div><strong>{entry.course_code || entry.course_name}</strong><span>{entry.day} · {formatClock(entry.start_time)} – {formatClock(entry.end_time)}</span><small>{entry.section ? `Section ${entry.section}` : 'Shared'} · {entry.room || 'Room TBA'}</small></div></label>)}</div>}<Field label="Notes"><Textarea value={notes} onChange={(e) => setNotes(e.target.value)} maxLength={2000} rows={4} placeholder="Explain what clashes and how it affects you."/></Field><Field label="Evidence reference" hint="Optional text/reference only; the backend contract does not expose file upload for report evidence."><Input value={evidence} onChange={(e) => setEvidence(e.target.value)} maxLength={500}/></Field>{selectedEntries.length > 0 && <small className="muted">Selected: {selectedEntries.map((entry) => entry.course_code).join(', ')}</small>}{error && <div className="form-error">{error}</div>}<div className="modal-actions"><button type="button" className="btn btn--secondary" onClick={onClose}>Cancel</button><button className="btn btn--primary" disabled={busy}>{busy ? 'Submitting…' : 'Submit report'}</button></div></form></Modal>
}

function ReviewModal({ report, onClose, onSaved }: { report: ClashReportDetail; onClose: () => void; onSaved: () => Promise<void> }) {
  const allowed: ClashReportStatus[] = report.status === 'submitted' ? ['under_review','rejected','duplicate'] : ['resolved','rejected','duplicate']
  const [status, setStatus] = useState<ClashReportStatus>(allowed[0]); const [reason, setReason] = useState<ClashReportResolutionReason>('timetable_changed'); const [note, setNote] = useState(''); const [duplicateId, setDuplicateId] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  async function submit(event: FormEvent) { event.preventDefault(); const terminal = ['resolved','rejected','duplicate'].includes(status); if (terminal && !note.trim()) { setError('A resolution note is required for terminal statuses.'); return } if (status === 'duplicate' && !Number(duplicateId)) { setError('Duplicate reports require the original report ID.'); return } setBusy(true); setError(''); try { await reportsApi.review(report.id, { status, resolution_note: terminal ? note : null, resolution_reason: status === 'resolved' ? reason : null, duplicate_of_report_id: status === 'duplicate' ? Number(duplicateId) : null }); await onSaved() } catch (err) { setError(err instanceof ApiError ? err.message : 'Unable to update report.') } finally { setBusy(false) } }
  return <Modal title={`Update case #${report.id}`} onClose={onClose}><form className="form-stack" onSubmit={submit}><Field label="Next status"><Select value={status} onChange={(e) => setStatus(e.target.value as ClashReportStatus)}>{allowed.map((item) => <option key={item} value={item}>{titleCase(item)}</option>)}</Select></Field>{status === 'resolved' && <Field label="Verified resolution reason" hint="The backend checks this reason against the student's live timetable and enrollments."><Select value={reason} onChange={(e) => setReason(e.target.value as ClashReportResolutionReason)}>{resolutionReasons.map((item) => <option key={item} value={item}>{titleCase(item)}</option>)}</Select></Field>}{status === 'duplicate' && <Field label="Original report ID"><Input type="number" min={1} value={duplicateId} onChange={(e) => setDuplicateId(e.target.value)} required/></Field>}<Field label={['resolved','rejected','duplicate'].includes(status) ? 'Resolution note' : 'Review note'}><Textarea value={note} onChange={(e) => setNote(e.target.value)} maxLength={2000} rows={4}/></Field>{error && <div className="form-error">{error}</div>}<div className="modal-actions"><button type="button" className="btn btn--secondary" onClick={onClose}>Cancel</button><button className="btn btn--primary" disabled={busy}>Save status</button></div></form></Modal>
}
