import { Plus, Trash2 } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { facultyApi } from '../api/faculty'
import { ApiError } from '../api/client'
import { Field, Input, Select } from '../components/Form'
import { EmptyState, ErrorNote, ErrorState, LoadingState, PageHeader, Section, SuccessNote } from '../components/Ui'
import { useAuth } from '../features/auth/AuthContext'
import { useAsync } from '../hooks/useAsync'

export function FacultyAssignmentsPage() {
  const { user } = useAuth(); const manager = user && ['coordinator','admin'].includes(user.role)
  const assignments = useAsync(() => manager ? facultyApi.managedAssignments() : facultyApi.assignments(), [manager])
  const [facultySearch, setFacultySearch] = useState('')
  const facultyUsers = useAsync(async () => manager ? facultyApi.directory(facultySearch, 0, 100) : null, [manager, facultySearch])
  const [facultyId, setFacultyId] = useState(''); const [code, setCode] = useState(''); const [section, setSection] = useState(''); const [semester, setSemester] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [adding, setAdding] = useState(false); const [removingId, setRemovingId] = useState<number | null>(null)
  async function add(event: FormEvent) { event.preventDefault(); if (adding) return; setAdding(true); setError(''); setMessage(''); try { await facultyApi.addAssignment({ faculty_user_id: Number(facultyId), course_code: code, section, semester }); setMessage('Faculty assignment created.'); setCode(''); setSection(''); setSemester(''); await assignments.reload() } catch (err) { setError(err instanceof ApiError ? err.message : 'Unable to create assignment.') } finally { setAdding(false) } }
  async function remove(id: number) { if (!window.confirm('Remove this faculty assignment?')) return; setRemovingId(id); setError(''); setMessage(''); try { await facultyApi.removeAssignment(id); setMessage('Faculty assignment removed.'); await assignments.reload() } catch (err) { setError(err instanceof ApiError ? err.message : 'Unable to remove assignment.') } finally { setRemovingId(null) } }
  return <div className="page"><PageHeader title={manager ? 'Faculty assignments' : 'My assignments'} description={manager ? 'Map faculty accounts to stable course, section and semester identities.' : 'The course mappings used to derive your teaching timetable.'}/>{message && <SuccessNote>{message}</SuccessNote>}{error && <ErrorNote>{error}</ErrorNote>}{manager && <Section title="Add faculty assignment"><form className="form-grid" onSubmit={add}><Field label="Find faculty" hint="Search active faculty accounts by name or email."><Input value={facultySearch} onChange={(e) => { setFacultySearch(e.target.value); setFacultyId('') }} maxLength={200} placeholder="Name or university email"/></Field><Field label="Faculty member"><Select value={facultyId} onChange={(e) => setFacultyId(e.target.value)} disabled={facultyUsers.loading} required><option value="">{facultyUsers.loading ? 'Searching…' : facultyUsers.data?.faculty.length ? 'Select faculty' : 'No active faculty found'}</option>{facultyUsers.data?.faculty.map((member) => <option value={member.id} key={member.id}>{member.full_name} · {member.email}</option>)}</Select></Field><Field label="Course code"><Input value={code} onChange={(e) => setCode(e.target.value)} maxLength={50} required/></Field><Field label="Section"><Input value={section} onChange={(e) => setSection(e.target.value)} maxLength={50} required/></Field><Field label="Semester"><Input value={semester} onChange={(e) => setSemester(e.target.value)} maxLength={50} required/></Field><div className="form-grid__full"><button className="btn btn--primary" disabled={adding || removingId !== null || !Number(facultyId)}><Plus size={16}/>{adding ? 'Adding…' : 'Add assignment'}</button></div></form></Section>}
    <Section title={manager ? 'Managed assignments' : 'Assigned courses'}>{assignments.loading ? <LoadingState/> : assignments.error ? <ErrorState message={assignments.error} retry={assignments.reload}/> : assignments.data?.length ? <div className="table-wrap"><table className="data-table"><thead><tr><th>Faculty</th><th>Course</th><th>Section</th><th>Semester</th>{manager && <th>Action</th>}</tr></thead><tbody>{assignments.data.map((item) => <tr key={item.id}><td><strong>{item.faculty_name}</strong><small>{item.faculty_email}</small></td><td>{item.course_code}</td><td>{item.section}</td><td>{item.semester}</td>{manager && <td><button className="icon-btn icon-btn--danger" disabled={removingId !== null} onClick={() => void remove(item.id)} aria-label="Remove assignment"><Trash2 size={16}/></button></td>}</tr>)}</tbody></table></div> : <EmptyState title="No faculty assignments" description="No stable faculty course mappings are available for this view."/>}</Section></div>
}
