import { BellRing, CheckCheck, Clock, Play } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { notificationsApi } from '../api/notifications'
import { ApiError } from '../api/client'
import { Field, Input, Select } from '../components/Form'
import { EmptyState, ErrorNote, ErrorState, LoadingState, PageHeader, Pagination, Section, SuccessNote } from '../components/Ui'
import { useAuth } from '../features/auth/AuthContext'
import { useAsync } from '../hooks/useAsync'
import type { NotificationPreference, NotificationType } from '../types/api'
import { formatRelative, titleCase } from '../utils/format'

const types: NotificationType[] = ['class_reminder','daily_summary','schedule_change','room_change','time_change','cancellation','clash_report_status']
const PAGE_SIZE = 20

export function NotificationsPage() {
  const { user } = useAuth(); const [unreadOnly, setUnreadOnly] = useState(false); const [type, setType] = useState<NotificationType | ''>(''); const [offset, setOffset] = useState(0); const [message, setMessage] = useState(''); const [actionError, setActionError] = useState(''); const [busyAction, setBusyAction] = useState<string | null>(null)
  const inbox = useAsync(() => notificationsApi.list({ unreadOnly, type, offset, limit: PAGE_SIZE }), [unreadOnly, type, offset])
  const prefs = useAsync(() => notificationsApi.preferences(), [])
  async function read(id: number) { if (busyAction) return; setBusyAction(`read-${id}`); setActionError(''); setMessage(''); try { await notificationsApi.markRead(id); await inbox.reload() } catch (err) { setActionError(err instanceof ApiError ? err.message : 'Unable to mark the notification as read.') } finally { setBusyAction(null) } }
  async function readAll() { if (busyAction) return; setBusyAction('read-all'); setActionError(''); setMessage(''); try { await notificationsApi.markAllRead(); setMessage('All notifications marked as read.'); await inbox.reload() } catch (err) { setActionError(err instanceof ApiError ? err.message : 'Unable to mark notifications as read.') } finally { setBusyAction(null) } }
  async function processJobs() { if (busyAction) return; setBusyAction('jobs'); setActionError(''); setMessage(''); try { const result = await notificationsApi.processJobs(); setMessage(`Notification job processed ${result.processed_users} users and created ${result.reminders_created} reminders.`); await inbox.reload() } catch (err) { setActionError(err instanceof ApiError ? err.message : 'Unable to process notification jobs.') } finally { setBusyAction(null) } }

  return <div className="page"><PageHeader title="Notifications & reminders" description="Your UniTime-AI inbox for class reminders, schedule changes and clash-report updates." actions={<div className="button-row"><button className="btn btn--secondary" disabled={busyAction !== null || !inbox.data?.unread_count} onClick={() => void readAll()}><CheckCheck size={16}/>{busyAction === 'read-all' ? 'Updating…' : 'Mark all read'}</button>{user && ['coordinator','admin'].includes(user.role) && <button className="btn btn--primary" disabled={busyAction !== null} onClick={() => void processJobs()}><Play size={16}/>{busyAction === 'jobs' ? 'Processing…' : 'Process jobs'}</button>}</div>}/>{message && <SuccessNote>{message}</SuccessNote>}{actionError && <ErrorNote>{actionError}</ErrorNote>}
    <div className="notifications-layout"><Section title={`Inbox${inbox.data ? ` · ${inbox.data.unread_count} unread` : ''}`} actions={<div className="inline-filters"><label><input type="checkbox" checked={unreadOnly} onChange={(e) => { setUnreadOnly(e.target.checked); setOffset(0) }}/>Unread only</label><Select value={type} onChange={(e) => { setType(e.target.value as NotificationType | ''); setOffset(0) }}><option value="">All types</option>{types.map((item) => <option value={item} key={item}>{titleCase(item)}</option>)}</Select></div>}>{inbox.loading ? <LoadingState/> : inbox.error ? <ErrorState message={inbox.error} retry={inbox.reload}/> : inbox.data?.notifications.length ? <div className="notification-list">{inbox.data.notifications.map((item) => <article key={item.id} className={item.read_at ? '' : 'notification-list__unread'}><div className="notification-icon"><BellRing size={17}/></div><div><div className="notification-list__heading"><strong>{item.title}</strong><span>{titleCase(item.type)}</span></div><p>{item.message}</p><small><Clock size={12}/>{formatRelative(item.created_at)}</small></div>{!item.read_at && <button className="btn btn--ghost" disabled={busyAction !== null} onClick={() => void read(item.id)}>{busyAction === `read-${item.id}` ? 'Updating…' : 'Mark read'}</button>}</article>)}</div> : <EmptyState title="Nothing here" description="Your current notification filter has no items."/>}{inbox.data && <Pagination total={inbox.data.total} offset={inbox.data.offset} limit={inbox.data.limit} label="notifications" onChange={setOffset}/>}</Section><Section title="Reminder preferences" description="These settings are stored by the backend for your account.">{prefs.loading ? <LoadingState/> : prefs.error ? <ErrorState message={prefs.error} retry={prefs.reload}/> : prefs.data ? <PreferenceForm initial={prefs.data} onSaved={async () => { setActionError(''); setMessage('Notification preferences saved.'); await prefs.reload() }}/> : null}</Section></div>
  </div>
}

function PreferenceForm({ initial, onSaved }: { initial: NotificationPreference; onSaved: () => Promise<void> }) {
  const [minutes, setMinutes] = useState<string>(initial.class_reminder_minutes === null ? '' : String(initial.class_reminder_minutes)); const [daily, setDaily] = useState(Boolean(initial.daily_summary_enabled)); const [time, setTime] = useState(initial.daily_summary_time || '07:00'); const [schedule, setSchedule] = useState(Boolean(initial.schedule_change_enabled)); const [reports, setReports] = useState(Boolean(initial.clash_report_updates_enabled)); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { await notificationsApi.updatePreferences({ class_reminder_minutes: minutes ? Number(minutes) as 5|10|15|30 : null, daily_summary_enabled: daily, daily_summary_time: time, schedule_change_enabled: schedule, clash_report_updates_enabled: reports }); await onSaved() } catch (err) { setError(err instanceof ApiError ? err.message : 'Unable to save preferences.') } finally { setBusy(false) } }
  return <form className="form-stack" onSubmit={submit}><Field label="Class reminder"><Select value={minutes} onChange={(e) => setMinutes(e.target.value)}><option value="">Off</option>{[5,10,15,30].map((value) => <option key={value} value={value}>{value} minutes before</option>)}</Select></Field><label className="switch-row"><div><strong>Daily summary</strong><span>Receive your day's schedule summary.</span></div><input type="checkbox" checked={daily} onChange={(e) => setDaily(e.target.checked)}/></label>{daily && <Field label="Summary time"><Input type="time" value={time} onChange={(e) => setTime(e.target.value)}/></Field>}<label className="switch-row"><div><strong>Schedule changes</strong><span>Room, time and cancellation changes.</span></div><input type="checkbox" checked={schedule} onChange={(e) => setSchedule(e.target.checked)}/></label><label className="switch-row"><div><strong>Clash report updates</strong><span>Changes to submitted student reports.</span></div><input type="checkbox" checked={reports} onChange={(e) => setReports(e.target.checked)}/></label>{error && <div className="form-error">{error}</div>}<button className="btn btn--primary" disabled={busy}>{busy ? 'Saving…' : 'Save preferences'}</button></form>
}
